### ISSUE TITLE
Errors in generate-polls

### ISSUE THREAD

**Issue by Eadom** [trailofbits/cb-multios#42]
I enjoy this awesome project. But I found two errors when I run `./genpools.sh` to generate polls.

**The first is 'No module named support' in 'machine.py'.** 

I found some 'machine.py' import 'support' via 

```
sys.path.append(join(dirname(dirname(dirname(abspath(__file__)))), "support"))
import support as sp
```
**However, the dictionary is deleted.** 

**The second is "'module' object has no attribute 'cgc_sin'".** 

The 'machine.py' uses `math.cgc_sin` but there is no 'cgc_sin' in 'math'. I check the original cgc repository. The code was `math.sin`. Then I made a diff of these two files.

```
28,29c28,29
<         print args, math.cgc_sqrt(variance)
<     return math.cgc_sqrt(variance)
---
>         print args, math.sqrt(variance)
>     return math.sqrt(variance)
137,139c137,139
<         Op('COS', 1, f=lambda args: math.cgc_cos(args[0])),
<         Op('LN', 1, f=lambda args: math.cgc_log(args[0])),
<         Op('LOG10', 1, f=lambda args: math.cgc_log10(args[0])),
---
>         Op('COS', 1, f=lambda args: math.cos(args[0])),
>         Op('LN', 1, f=lambda args: math.log(args[0])),
>         Op('LOG10', 1, f=lambda args: math.log10(args[0])),
143,144c143,144
<         Op('SIN', 1, f=lambda args: math.cgc_sin(args[0])),
<         Op('SQRT', 1, f=lambda args: math.cgc_sqrt(args[0])),
---
>         Op('SIN', 1, f=lambda args: math.sin(args[0])),
>         Op('SQRT', 1, f=lambda args: math.sqrt(args[0])),
```

**Is there a mistake introduced by global replacing?** 

Error Traceback:
```
A_Game_of_Chance
Traceback (most recent call last):
  File "/root/cb-multios/tools/generate-polls/generate-polls", line 267, in <module>
    main()
  File "/root/cb-multios/tools/generate-polls/generate-polls", line 165, in main
    machine = get_state_machine(args.machine)
  File "/root/cb-multios/tools/generate-polls/generate-polls", line 117, in get_state_machine
    module = imp.load_source('state_machine', filename)
  File "poller/for-release//machine.py", line 30, in <module>
    import support as sp
ImportError: No module named support
Accel
Traceback (most recent call last):
  File "/root/cb-multios/tools/generate-polls/generate-polls", line 267, in <module>
    main()
  File "/root/cb-multios/tools/generate-polls/generate-polls", line 226, in main
    graph.walk(current_id, total)
  File "/root/cb-multios/tools/generate-polls/generator/graph.py", line 231, in walk
    response = node()
  File "poller/for-release//machine.py", line 261, in quit
    self._show(k)
  File "poller/for-release//machine.py", line 189, in _show
    value = value.evaluate()
  File "poller/for-release//machine.py", line 104, in evaluate
    result = round(self.op.evaluate(map(lambda x: x.evaluate(), self.args)), 3)
  File "poller/for-release//machine.py", line 104, in <lambda>
    result = round(self.op.evaluate(map(lambda x: x.evaluate(), self.args)), 3)
  File "poller/for-release//machine.py", line 104, in evaluate
    result = round(self.op.evaluate(map(lambda x: x.evaluate(), self.args)), 3)
  File "poller/for-release//machine.py", line 104, in <lambda>
    result = round(self.op.evaluate(map(lambda x: x.evaluate(), self.args)), 3)
  File "poller/for-release//machine.py", line 104, in evaluate
    result = round(self.op.evaluate(map(lambda x: x.evaluate(), self.args)), 3)
  File "poller/for-release//machine.py", line 127, in evaluate
    return self.f(args)
  File "poller/for-release//machine.py", line 143, in <lambda>
    Op('SIN', 1, f=lambda args: math.cgc_sin(args[0])),
AttributeError: 'module' object has no attribute 'cgc_sin'
```

**Comment by woodruffw** [comment]
Should be fixed by #43; let me know if it isn't.
